language: node_js
node_js:
   - node
dist: trusty
sudo: required
addons:
    chrome: stable
cache:
    npm: true
    directories:
        - node_modules
before_script:
  - npm install -g --silent @angular/cli

script:
   - ng lint
   - ng test

notifications:
    on_failure: change
    on_success: change
