language: node_js
node_js:
   - node
dist: trusty
sudo: required
addons:
    chrome: stable
services:
   - docker
cache:
    directories:
        - node_modules
before_script:
  - docker swarm init
  - docker stack deploy -c docker-compose-api.yml docks-api
  - npm install -g --silent @angular/cli
  - ./scripts/wait-for-docks.sh
script:
   - ng lint
   - ng build --prod --no-progress
   - ng test --no-progress
notifications:
  email:
    on_success: change
    on_failure: change