# Deploy Docks UI using an image from a local registry
# Used for building and deploying Docks UI to a swarm

version: '3.2'

services:
  ui:
    image: 127.0.0.1:5000/docks-ui:local
    ports:
      - 4200:80
    environment:
      - DOCKS_API_ADDRESS=http://127.0.0.1:8080
