version: '3.2'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "4200:4200"
