# Deploy the latest version of Docks UI using an image from Docker Hub
# Used for production

version: '3.3'

services:
  ui:
    image: tripleparity/docks-ui:0.4.0
    ports:
      - 4200:80
    environment:
      - DOCKS_API_ADDRESS=http://127.0.0.1:8080
